<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-04T18:24:55 CEST" name="Suite" finished-at="2025-05-04T18:26:16 CEST" duration-ms="80845">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" name="loginErrorValidation" class="practiceSeleniumFramework.tests.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.productErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" name="productErrorValidation" class="practiceSeleniumFramework.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" name="SubmitOrder" class="practiceSeleniumFramework.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-05-04T18:24:55 CEST" name="Error Validation Test" finished-at="2025-05-04T18:25:15 CEST" duration-ms="19811">
      <class name="practiceSeleniumFramework.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:24:55 CEST" name="launchApplication" finished-at="2025-05-04T18:25:03 CEST" duration-ms="7668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:25:03 CEST" name="loginErrorValidation" finished-at="2025-05-04T18:25:03 CEST" duration-ms="428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:25:03 CEST" name="tearDown" finished-at="2025-05-04T18:25:05 CEST" duration-ms="1336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:25:05 CEST" name="launchApplication" finished-at="2025-05-04T18:25:13 CEST" duration-ms="8026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:25:13 CEST" name="productErrorValidation" finished-at="2025-05-04T18:25:14 CEST" duration-ms="915" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at practiceSeleniumFramework.pageObjects.ProductCataloguePage.addProductToCart(ProductCataloguePage.java:46)
at practiceSeleniumFramework.tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@1df8b5b8]" started-at="2025-05-04T18:25:14 CEST" name="tearDown" finished-at="2025-05-04T18:25:15 CEST" duration-ms="1121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practiceSeleniumFramework.tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2025-05-04T18:24:55 CEST" name="Submit Order Test" finished-at="2025-05-04T18:26:16 CEST" duration-ms="80845">
      <class name="practiceSeleniumFramework.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:24:56 CEST" name="launchApplication" finished-at="2025-05-04T18:25:04 CEST" duration-ms="8466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:04 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-04T18:25:28 CEST" duration-ms="24230" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravani@1410, email=sravanisravs1410@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Item not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Item not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at practiceSeleniumFramework.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:28 CEST" name="tearDown" finished-at="2025-05-04T18:25:29 CEST" duration-ms="1080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:29 CEST" name="launchApplication" finished-at="2025-05-04T18:25:37 CEST" duration-ms="7797" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:37 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-04T18:25:40 CEST" duration-ms="2278" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravani@1410, email=sravanisravs1410@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[Element <button class="btn btn-custom"> is not clickable at point (1297,27) because another element <div class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating"> obscures it
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [bb3bd430-32c8-4a44-9623-497c177b3cac, clickElement {id=8f518e85-5b17-4a8f-a549-7659497a4e9a}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.1, moz:accessibilityChecks: false, moz:buildID: 20250430203103, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 44792, moz:profile: C:\Users\methu\AppData\Loca..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (bb3bd430-32c8-4a44-9623-497c177b3cac)] -> css selector: [routerlink*='cart']]
Session ID: bb3bd430-32c8-4a44-9623-497c177b3cac]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <button class="btn btn-custom"> is not clickable at point (1297,27) because another element <div class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating"> obscures it
Build info: version: '4.31.0', revision: '1ef9f18787*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [bb3bd430-32c8-4a44-9623-497c177b3cac, clickElement {id=8f518e85-5b17-4a8f-a549-7659497a4e9a}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.1, moz:accessibilityChecks: false, moz:buildID: 20250430203103, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 44792, moz:profile: C:\Users\methu\AppData\Loca..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (bb3bd430-32c8-4a44-9623-497c177b3cac)] -> css selector: [routerlink*='cart']]
Session ID: bb3bd430-32c8-4a44-9623-497c177b3cac
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy16.click(Unknown Source)
at practiceSeleniumFramework.abstractComponents.AbstractComponent.goToCartPage(AbstractComponent.java:31)
at practiceSeleniumFramework.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:40 CEST" name="tearDown" finished-at="2025-05-04T18:25:41 CEST" duration-ms="1702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:41 CEST" name="launchApplication" finished-at="2025-05-04T18:25:49 CEST" duration-ms="8091" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:25:49 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-04T18:26:05 CEST" duration-ms="15723" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravanisai@22, email=methukulasravani@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:26:05 CEST" name="tearDown" finished-at="2025-05-04T18:26:06 CEST" duration-ms="1003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:26:06 CEST" name="launchApplication" finished-at="2025-05-04T18:26:14 CEST" duration-ms="7749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:26:14 CEST" name="OrderHistoryTest" finished-at="2025-05-04T18:26:15 CEST" depends-on-methods="practiceSeleniumFramework.tests.SubmitOrderTest.SubmitOrder" duration-ms="861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@e3b3b2f]" started-at="2025-05-04T18:26:15 CEST" name="tearDown" finished-at="2025-05-04T18:26:16 CEST" duration-ms="1335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practiceSeleniumFramework.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
